name: Javadocs

on:
  pull_request:
    branches: 
      - master

jobs:
  windup-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        java-package: jdk
        cache: maven
    - name: Install
      run: mvn install -DskipTests
    - name: Javadocs
      run: mvn validate -PjavadocDist -DskipTests -Djavadoc.branding="Windup 0.0.0.Final Javadoc"
    - name: Zip
      run: zip -r target.zip target/
    - uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: target.zip
